// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload}
 */
@com.google.protobuf.Generated
public  final class ApproveSuggestionPayload extends
    com.google.protobuf.GeneratedMessageLite<
        ApproveSuggestionPayload, ApproveSuggestionPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload)
    ApproveSuggestionPayloadOrBuilder {
  private ApproveSuggestionPayload() {
    suggestionId_ = "";
  }
  public static final int SUGGESTION_ID_FIELD_NUMBER = 1;
  private java.lang.String suggestionId_;
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The suggestionId.
   */
  @java.lang.Override
  public java.lang.String getSuggestionId() {
    return suggestionId_;
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The bytes for suggestionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuggestionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(suggestionId_);
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @param value The suggestionId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSuggestionId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    suggestionId_ = value;
  }
  /**
   * <code>string suggestion_id = 1;</code>
   */
  private void clearSuggestionId() {

    suggestionId_ = getDefaultInstance().getSuggestionId();
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @param value The bytes for suggestionId to set.
   */
  private void setSuggestionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    suggestionId_ = value.toStringUtf8();

  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string suggestion_id = 1;</code>
     * @return The suggestionId.
     */
    @java.lang.Override
    public java.lang.String getSuggestionId() {
      return instance.getSuggestionId();
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @return The bytes for suggestionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSuggestionIdBytes() {
      return instance.getSuggestionIdBytes();
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @param value The suggestionId to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSuggestionId(value);
      return this;
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuggestionId() {
      copyOnWrite();
      instance.clearSuggestionId();
      return this;
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @param value The bytes for suggestionId to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSuggestionIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "suggestionId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload DEFAULT_INSTANCE;
  static {
    ApproveSuggestionPayload defaultInstance = new ApproveSuggestionPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ApproveSuggestionPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ApproveSuggestionPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ApproveSuggestionPayload> PARSER;

  public static com.google.protobuf.Parser<ApproveSuggestionPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

