// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface BufferWaitPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string track_id = 1;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 1;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <code>repeated string waiting_for = 2;</code>
   * @return A list containing the waitingFor.
   */
  java.util.List<java.lang.String>
      getWaitingForList();
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @return The count of waitingFor.
   */
  int getWaitingForCount();
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param index The index of the element to return.
   * @return The waitingFor at the given index.
   */
  java.lang.String getWaitingFor(int index);
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param index The index of the element to return.
   * @return The waitingFor at the given index.
   */
  com.google.protobuf.ByteString
      getWaitingForBytes(int index);
}
