// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializebufferReadyPayload")
public inline fun bufferReadyPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload`
 */
public object BufferReadyPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload = _builder.build()

    /**
     * `string track_id = 1;`
     */
    public var trackId: kotlin.String
      @kotlin.jvm.JvmName("getTrackId")
        get() = _builder.trackId
      @kotlin.jvm.JvmName("setTrackId")
        set(value) {
        _builder.trackId = value
      }
    /**
     * `string track_id = 1;`
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.BufferReadyPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferReadyPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.BufferReadyPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

