// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload}
 */
@com.google.protobuf.Generated
public  final class BufferWaitPayload extends
    com.google.protobuf.GeneratedMessageLite<
        BufferWaitPayload, BufferWaitPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload)
    BufferWaitPayloadOrBuilder {
  private BufferWaitPayload() {
    trackId_ = "";
    waitingFor_ = emptyProtobufList();
  }
  public static final int TRACK_ID_FIELD_NUMBER = 1;
  private java.lang.String trackId_;
  /**
   * <code>string track_id = 1;</code>
   * @return The trackId.
   */
  @java.lang.Override
  public java.lang.String getTrackId() {
    return trackId_;
  }
  /**
   * <code>string track_id = 1;</code>
   * @return The bytes for trackId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTrackIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(trackId_);
  }
  /**
   * <code>string track_id = 1;</code>
   * @param value The trackId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTrackId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    trackId_ = value;
  }
  /**
   * <code>string track_id = 1;</code>
   */
  private void clearTrackId() {

    trackId_ = getDefaultInstance().getTrackId();
  }
  /**
   * <code>string track_id = 1;</code>
   * @param value The bytes for trackId to set.
   */
  private void setTrackIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    trackId_ = value.toStringUtf8();

  }

  public static final int WAITING_FOR_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> waitingFor_;
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @return A list containing the waitingFor.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getWaitingForList() {
    return waitingFor_;
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @return The count of waitingFor.
   */
  @java.lang.Override
  public int getWaitingForCount() {
    return waitingFor_.size();
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param index The index of the element to return.
   * @return The waitingFor at the given index.
   */
  @java.lang.Override
  public java.lang.String getWaitingFor(int index) {
    return waitingFor_.get(index);
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the waitingFor at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWaitingForBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        waitingFor_.get(index));
  }
  private void ensureWaitingForIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        waitingFor_;  if (!tmp.isModifiable()) {
      waitingFor_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param index The index to set the value at.
   * @param value The waitingFor to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setWaitingFor(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureWaitingForIsMutable();
    waitingFor_.set(index, value);
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param value The waitingFor to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addWaitingFor(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureWaitingForIsMutable();
    waitingFor_.add(value);
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param values The waitingFor to add.
   */
  private void addAllWaitingFor(
      java.lang.Iterable<java.lang.String> values) {
    ensureWaitingForIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, waitingFor_);
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   */
  private void clearWaitingFor() {
    waitingFor_ = emptyProtobufList();
  }
  /**
   * <code>repeated string waiting_for = 2;</code>
   * @param value The bytes of the waitingFor to add.
   */
  private void addWaitingForBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureWaitingForIsMutable();
    waitingFor_.add(value.toStringUtf8());
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string track_id = 1;</code>
     * @return The trackId.
     */
    @java.lang.Override
    public java.lang.String getTrackId() {
      return instance.getTrackId();
    }
    /**
     * <code>string track_id = 1;</code>
     * @return The bytes for trackId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      return instance.getTrackIdBytes();
    }
    /**
     * <code>string track_id = 1;</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTrackId(value);
      return this;
    }
    /**
     * <code>string track_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      copyOnWrite();
      instance.clearTrackId();
      return this;
    }
    /**
     * <code>string track_id = 1;</code>
     * @param value The bytes for trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTrackIdBytes(value);
      return this;
    }

    /**
     * <code>repeated string waiting_for = 2;</code>
     * @return A list containing the waitingFor.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getWaitingForList() {
      return java.util.Collections.unmodifiableList(
          instance.getWaitingForList());
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @return The count of waitingFor.
     */
    @java.lang.Override
    public int getWaitingForCount() {
      return instance.getWaitingForCount();
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param index The index of the element to return.
     * @return The waitingFor at the given index.
     */
    @java.lang.Override
    public java.lang.String getWaitingFor(int index) {
      return instance.getWaitingFor(index);
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the waitingFor at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWaitingForBytes(int index) {
      return instance.getWaitingForBytes(index);
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param index The index to set the value at.
     * @param value The waitingFor to set.
     * @return This builder for chaining.
     */
    public Builder setWaitingFor(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setWaitingFor(index, value);
      return this;
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param value The waitingFor to add.
     * @return This builder for chaining.
     */
    public Builder addWaitingFor(
        java.lang.String value) {
      copyOnWrite();
      instance.addWaitingFor(value);
      return this;
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param values The waitingFor to add.
     * @return This builder for chaining.
     */
    public Builder addAllWaitingFor(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllWaitingFor(values);
      return this;
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaitingFor() {
      copyOnWrite();
      instance.clearWaitingFor();
      return this;
    }
    /**
     * <code>repeated string waiting_for = 2;</code>
     * @param value The bytes of the waitingFor to add.
     * @return This builder for chaining.
     */
    public Builder addWaitingForBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addWaitingForBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "trackId_",
            "waitingFor_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u021a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload DEFAULT_INSTANCE;
  static {
    BufferWaitPayload defaultInstance = new BufferWaitPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BufferWaitPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.BufferWaitPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BufferWaitPayload> PARSER;

  public static com.google.protobuf.Parser<BufferWaitPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

