// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope}
 */
@com.google.protobuf.Generated
public  final class Envelope extends
    com.google.protobuf.GeneratedMessageLite<
        Envelope, Envelope.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope)
    EnvelopeOrBuilder {
  private Envelope() {
    type_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int TYPE_FIELD_NUMBER = 1;
  private java.lang.String type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    return type_;
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(type_);
  }
  /**
   * <code>string type = 1;</code>
   * @param value The type to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setType(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    type_ = value;
  }
  /**
   * <code>string type = 1;</code>
   */
  private void clearType() {

    type_ = getDefaultInstance().getType();
  }
  /**
   * <code>string type = 1;</code>
   * @param value The bytes for type to set.
   */
  private void setTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    type_ = value.toStringUtf8();

  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }
  /**
   * <code>bytes payload = 2;</code>
   * @param value The payload to set.
   */
  private void setPayload(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    payload_ = value;
  }
  /**
   * <code>bytes payload = 2;</code>
   */
  private void clearPayload() {

    payload_ = getDefaultInstance().getPayload();
  }

  public static final int COMPRESSED_FIELD_NUMBER = 3;
  private boolean compressed_;
  /**
   * <code>bool compressed = 3;</code>
   * @return The compressed.
   */
  @java.lang.Override
  public boolean getCompressed() {
    return compressed_;
  }
  /**
   * <code>bool compressed = 3;</code>
   * @param value The compressed to set.
   */
  private void setCompressed(boolean value) {
    
    compressed_ = value;
  }
  /**
   * <code>bool compressed = 3;</code>
   */
  private void clearCompressed() {

    compressed_ = false;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.EnvelopeOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return instance.getType();
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return instance.getTypeBytes();
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTypeBytes(value);
      return this;
    }

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return instance.getPayload();
    }
    /**
     * <code>bytes payload = 2;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayload(value);
      return this;
    }
    /**
     * <code>bytes payload = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }

    /**
     * <code>bool compressed = 3;</code>
     * @return The compressed.
     */
    @java.lang.Override
    public boolean getCompressed() {
      return instance.getCompressed();
    }
    /**
     * <code>bool compressed = 3;</code>
     * @param value The compressed to set.
     * @return This builder for chaining.
     */
    public Builder setCompressed(boolean value) {
      copyOnWrite();
      instance.setCompressed(value);
      return this;
    }
    /**
     * <code>bool compressed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressed() {
      copyOnWrite();
      instance.clearCompressed();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "type_",
            "payload_",
            "compressed_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\n" +
              "\u0003\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope DEFAULT_INSTANCE;
  static {
    Envelope defaultInstance = new Envelope();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Envelope.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.Envelope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Envelope> PARSER;

  public static com.google.protobuf.Parser<Envelope> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

