// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface HostChangedPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.HostChangedPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string new_host_id = 1;</code>
   * @return The newHostId.
   */
  java.lang.String getNewHostId();
  /**
   * <code>string new_host_id = 1;</code>
   * @return The bytes for newHostId.
   */
  com.google.protobuf.ByteString
      getNewHostIdBytes();

  /**
   * <code>string new_host_name = 2;</code>
   * @return The newHostName.
   */
  java.lang.String getNewHostName();
  /**
   * <code>string new_host_name = 2;</code>
   * @return The bytes for newHostName.
   */
  com.google.protobuf.ByteString
      getNewHostNameBytes();
}
