// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface JoinRejectedPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.JoinRejectedPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string reason = 1;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 1;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
