// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializepingPayload")
public inline fun pingPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload`
 */
public object PingPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload = _builder.build()

    /**
     * `int64 client_time = 1;`
     */
    public var clientTime: kotlin.Long
      @kotlin.jvm.JvmName("getClientTime")
        get() = _builder.clientTime
      @kotlin.jvm.JvmName("setClientTime")
        set(value) {
        _builder.clientTime = value
      }
    /**
     * `int64 client_time = 1;`
     */
    public fun clearClientTime() {
      _builder.clearClientTime()
    }

    /**
     * `int64 sequence = 2;`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * `int64 sequence = 2;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.PingPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PingPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.PingPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

