// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload}
 */
@com.google.protobuf.Generated
public  final class PlaybackActionPayload extends
    com.google.protobuf.GeneratedMessageLite<
        PlaybackActionPayload, PlaybackActionPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload)
    PlaybackActionPayloadOrBuilder {
  private PlaybackActionPayload() {
    action_ = "";
    trackId_ = "";
    queue_ = emptyProtobufList();
    queueTitle_ = "";
  }
  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private java.lang.String action_;
  /**
   * <code>string action = 1;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    return action_;
  }
  /**
   * <code>string action = 1;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(action_);
  }
  /**
   * <code>string action = 1;</code>
   * @param value The action to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAction(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    action_ = value;
  }
  /**
   * <code>string action = 1;</code>
   */
  private void clearAction() {

    action_ = getDefaultInstance().getAction();
  }
  /**
   * <code>string action = 1;</code>
   * @param value The bytes for action to set.
   */
  private void setActionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    action_ = value.toStringUtf8();

  }

  public static final int TRACK_ID_FIELD_NUMBER = 2;
  private java.lang.String trackId_;
  /**
   * <code>string track_id = 2;</code>
   * @return The trackId.
   */
  @java.lang.Override
  public java.lang.String getTrackId() {
    return trackId_;
  }
  /**
   * <code>string track_id = 2;</code>
   * @return The bytes for trackId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTrackIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(trackId_);
  }
  /**
   * <code>string track_id = 2;</code>
   * @param value The trackId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTrackId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    trackId_ = value;
  }
  /**
   * <code>string track_id = 2;</code>
   */
  private void clearTrackId() {

    trackId_ = getDefaultInstance().getTrackId();
  }
  /**
   * <code>string track_id = 2;</code>
   * @param value The bytes for trackId to set.
   */
  private void setTrackIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    trackId_ = value.toStringUtf8();

  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private long position_;
  /**
   * <code>int64 position = 3;</code>
   * @return The position.
   */
  @java.lang.Override
  public long getPosition() {
    return position_;
  }
  /**
   * <code>int64 position = 3;</code>
   * @param value The position to set.
   */
  private void setPosition(long value) {
    
    position_ = value;
  }
  /**
   * <code>int64 position = 3;</code>
   */
  private void clearPosition() {

    position_ = 0L;
  }

  public static final int TRACK_INFO_FIELD_NUMBER = 4;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo trackInfo_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.Override
  public boolean hasTrackInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
    return trackInfo_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance() : trackInfo_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    trackInfo_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    if (trackInfo_ != null &&
        trackInfo_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance()) {
      trackInfo_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder(trackInfo_).mergeFrom(value).buildPartial();
    } else {
      trackInfo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  private void clearTrackInfo() {
    trackInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int INSERT_NEXT_FIELD_NUMBER = 5;
  private boolean insertNext_;
  /**
   * <code>bool insert_next = 5;</code>
   * @return The insertNext.
   */
  @java.lang.Override
  public boolean getInsertNext() {
    return insertNext_;
  }
  /**
   * <code>bool insert_next = 5;</code>
   * @param value The insertNext to set.
   */
  private void setInsertNext(boolean value) {
    
    insertNext_ = value;
  }
  /**
   * <code>bool insert_next = 5;</code>
   */
  private void clearInsertNext() {

    insertNext_ = false;
  }

  public static final int QUEUE_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> queue_;
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  public java.util.List<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder> 
      getQueueOrBuilderList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.Override
  public int getQueueCount() {
    return queue_.size();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
    return queue_.get(index);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder getQueueOrBuilder(
      int index) {
    return queue_.get(index);
  }
  private void ensureQueueIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> tmp = queue_;
    if (!tmp.isModifiable()) {
      queue_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.set(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  private void addAllQueue(
      java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
    ensureQueueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, queue_);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  private void clearQueue() {
    queue_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  private void removeQueue(int index) {
    ensureQueueIsMutable();
    queue_.remove(index);
  }

  public static final int QUEUE_TITLE_FIELD_NUMBER = 7;
  private java.lang.String queueTitle_;
  /**
   * <code>string queue_title = 7;</code>
   * @return The queueTitle.
   */
  @java.lang.Override
  public java.lang.String getQueueTitle() {
    return queueTitle_;
  }
  /**
   * <code>string queue_title = 7;</code>
   * @return The bytes for queueTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueueTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(queueTitle_);
  }
  /**
   * <code>string queue_title = 7;</code>
   * @param value The queueTitle to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setQueueTitle(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    queueTitle_ = value;
  }
  /**
   * <code>string queue_title = 7;</code>
   */
  private void clearQueueTitle() {

    queueTitle_ = getDefaultInstance().getQueueTitle();
  }
  /**
   * <code>string queue_title = 7;</code>
   * @param value The bytes for queueTitle to set.
   */
  private void setQueueTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    queueTitle_ = value.toStringUtf8();

  }

  public static final int VOLUME_FIELD_NUMBER = 8;
  private float volume_;
  /**
   * <code>float volume = 8;</code>
   * @return The volume.
   */
  @java.lang.Override
  public float getVolume() {
    return volume_;
  }
  /**
   * <code>float volume = 8;</code>
   * @param value The volume to set.
   */
  private void setVolume(float value) {
    
    volume_ = value;
  }
  /**
   * <code>float volume = 8;</code>
   */
  private void clearVolume() {

    volume_ = 0F;
  }

  public static final int SERVER_TIME_FIELD_NUMBER = 9;
  private long serverTime_;
  /**
   * <code>int64 server_time = 9;</code>
   * @return The serverTime.
   */
  @java.lang.Override
  public long getServerTime() {
    return serverTime_;
  }
  /**
   * <code>int64 server_time = 9;</code>
   * @param value The serverTime to set.
   */
  private void setServerTime(long value) {
    
    serverTime_ = value;
  }
  /**
   * <code>int64 server_time = 9;</code>
   */
  private void clearServerTime() {

    serverTime_ = 0L;
  }

  public static final int REVISION_FIELD_NUMBER = 10;
  private long revision_;
  /**
   * <code>int64 revision = 10;</code>
   * @return The revision.
   */
  @java.lang.Override
  public long getRevision() {
    return revision_;
  }
  /**
   * <code>int64 revision = 10;</code>
   * @param value The revision to set.
   */
  private void setRevision(long value) {
    
    revision_ = value;
  }
  /**
   * <code>int64 revision = 10;</code>
   */
  private void clearRevision() {

    revision_ = 0L;
  }

  public static final int CAPTURED_AT_SERVER_TIME_FIELD_NUMBER = 11;
  private long capturedAtServerTime_;
  /**
   * <code>int64 captured_at_server_time = 11;</code>
   * @return The capturedAtServerTime.
   */
  @java.lang.Override
  public long getCapturedAtServerTime() {
    return capturedAtServerTime_;
  }
  /**
   * <code>int64 captured_at_server_time = 11;</code>
   * @param value The capturedAtServerTime to set.
   */
  private void setCapturedAtServerTime(long value) {
    
    capturedAtServerTime_ = value;
  }
  /**
   * <code>int64 captured_at_server_time = 11;</code>
   */
  private void clearCapturedAtServerTime() {

    capturedAtServerTime_ = 0L;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      return instance.getAction();
    }
    /**
     * <code>string action = 1;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return instance.getActionBytes();
    }
    /**
     * <code>string action = 1;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      copyOnWrite();
      instance.setAction(value);
      return this;
    }
    /**
     * <code>string action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      copyOnWrite();
      instance.clearAction();
      return this;
    }
    /**
     * <code>string action = 1;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionBytes(value);
      return this;
    }

    /**
     * <code>string track_id = 2;</code>
     * @return The trackId.
     */
    @java.lang.Override
    public java.lang.String getTrackId() {
      return instance.getTrackId();
    }
    /**
     * <code>string track_id = 2;</code>
     * @return The bytes for trackId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      return instance.getTrackIdBytes();
    }
    /**
     * <code>string track_id = 2;</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTrackId(value);
      return this;
    }
    /**
     * <code>string track_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      copyOnWrite();
      instance.clearTrackId();
      return this;
    }
    /**
     * <code>string track_id = 2;</code>
     * @param value The bytes for trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTrackIdBytes(value);
      return this;
    }

    /**
     * <code>int64 position = 3;</code>
     * @return The position.
     */
    @java.lang.Override
    public long getPosition() {
      return instance.getPosition();
    }
    /**
     * <code>int64 position = 3;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(long value) {
      copyOnWrite();
      instance.setPosition(value);
      return this;
    }
    /**
     * <code>int64 position = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      copyOnWrite();
      instance.clearPosition();
      return this;
    }

    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    @java.lang.Override
    public boolean hasTrackInfo() {
      return instance.hasTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
      return instance.getTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setTrackInfo(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder setTrackInfo(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setTrackInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.mergeTrackInfo(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder clearTrackInfo() {  copyOnWrite();
      instance.clearTrackInfo();
      return this;
    }

    /**
     * <code>bool insert_next = 5;</code>
     * @return The insertNext.
     */
    @java.lang.Override
    public boolean getInsertNext() {
      return instance.getInsertNext();
    }
    /**
     * <code>bool insert_next = 5;</code>
     * @param value The insertNext to set.
     * @return This builder for chaining.
     */
    public Builder setInsertNext(boolean value) {
      copyOnWrite();
      instance.setInsertNext(value);
      return this;
    }
    /**
     * <code>bool insert_next = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInsertNext() {
      copyOnWrite();
      instance.clearInsertNext();
      return this;
    }

    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
      return java.util.Collections.unmodifiableList(
          instance.getQueueList());
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    @java.lang.Override
    public int getQueueCount() {
      return instance.getQueueCount();
    }/**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
      return instance.getQueue(index);
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder addQueue(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder addAllQueue(
        java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
      copyOnWrite();
      instance.addAllQueue(values);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder clearQueue() {
      copyOnWrite();
      instance.clearQueue();
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
     */
    public Builder removeQueue(int index) {
      copyOnWrite();
      instance.removeQueue(index);
      return this;
    }

    /**
     * <code>string queue_title = 7;</code>
     * @return The queueTitle.
     */
    @java.lang.Override
    public java.lang.String getQueueTitle() {
      return instance.getQueueTitle();
    }
    /**
     * <code>string queue_title = 7;</code>
     * @return The bytes for queueTitle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueueTitleBytes() {
      return instance.getQueueTitleBytes();
    }
    /**
     * <code>string queue_title = 7;</code>
     * @param value The queueTitle to set.
     * @return This builder for chaining.
     */
    public Builder setQueueTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setQueueTitle(value);
      return this;
    }
    /**
     * <code>string queue_title = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueueTitle() {
      copyOnWrite();
      instance.clearQueueTitle();
      return this;
    }
    /**
     * <code>string queue_title = 7;</code>
     * @param value The bytes for queueTitle to set.
     * @return This builder for chaining.
     */
    public Builder setQueueTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setQueueTitleBytes(value);
      return this;
    }

    /**
     * <code>float volume = 8;</code>
     * @return The volume.
     */
    @java.lang.Override
    public float getVolume() {
      return instance.getVolume();
    }
    /**
     * <code>float volume = 8;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(float value) {
      copyOnWrite();
      instance.setVolume(value);
      return this;
    }
    /**
     * <code>float volume = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      copyOnWrite();
      instance.clearVolume();
      return this;
    }

    /**
     * <code>int64 server_time = 9;</code>
     * @return The serverTime.
     */
    @java.lang.Override
    public long getServerTime() {
      return instance.getServerTime();
    }
    /**
     * <code>int64 server_time = 9;</code>
     * @param value The serverTime to set.
     * @return This builder for chaining.
     */
    public Builder setServerTime(long value) {
      copyOnWrite();
      instance.setServerTime(value);
      return this;
    }
    /**
     * <code>int64 server_time = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerTime() {
      copyOnWrite();
      instance.clearServerTime();
      return this;
    }

    /**
     * <code>int64 revision = 10;</code>
     * @return The revision.
     */
    @java.lang.Override
    public long getRevision() {
      return instance.getRevision();
    }
    /**
     * <code>int64 revision = 10;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(long value) {
      copyOnWrite();
      instance.setRevision(value);
      return this;
    }
    /**
     * <code>int64 revision = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      copyOnWrite();
      instance.clearRevision();
      return this;
    }

    /**
     * <code>int64 captured_at_server_time = 11;</code>
     * @return The capturedAtServerTime.
     */
    @java.lang.Override
    public long getCapturedAtServerTime() {
      return instance.getCapturedAtServerTime();
    }
    /**
     * <code>int64 captured_at_server_time = 11;</code>
     * @param value The capturedAtServerTime to set.
     * @return This builder for chaining.
     */
    public Builder setCapturedAtServerTime(long value) {
      copyOnWrite();
      instance.setCapturedAtServerTime(value);
      return this;
    }
    /**
     * <code>int64 captured_at_server_time = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapturedAtServerTime() {
      copyOnWrite();
      instance.clearCapturedAtServerTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "action_",
            "trackId_",
            "position_",
            "trackInfo_",
            "insertNext_",
            "queue_",
            com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.class,
            "queueTitle_",
            "volume_",
            "serverTime_",
            "revision_",
            "capturedAtServerTime_",
          };
          java.lang.String info =
              "\u0000\u000b\u0000\u0001\u0001\u000b\u000b\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0002\u0004\u1009\u0000\u0005\u0007\u0006\u001b\u0007\u0208\b\u0001\t\u0002" +
              "\n\u0002\u000b\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload DEFAULT_INSTANCE;
  static {
    PlaybackActionPayload defaultInstance = new PlaybackActionPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PlaybackActionPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PlaybackActionPayload> PARSER;

  public static com.google.protobuf.Parser<PlaybackActionPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

