// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface PlaybackActionPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PlaybackActionPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string action = 1;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 1;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string track_id = 2;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 2;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <code>int64 position = 3;</code>
   * @return The position.
   */
  long getPosition();

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   * @return Whether the trackInfo field is set.
   */
  boolean hasTrackInfo();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   * @return The trackInfo.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo();

  /**
   * <code>bool insert_next = 5;</code>
   * @return The insertNext.
   */
  boolean getInsertNext();

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> 
      getQueueList();
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index);
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 6;</code>
   */
  int getQueueCount();

  /**
   * <code>string queue_title = 7;</code>
   * @return The queueTitle.
   */
  java.lang.String getQueueTitle();
  /**
   * <code>string queue_title = 7;</code>
   * @return The bytes for queueTitle.
   */
  com.google.protobuf.ByteString
      getQueueTitleBytes();

  /**
   * <code>float volume = 8;</code>
   * @return The volume.
   */
  float getVolume();

  /**
   * <code>int64 server_time = 9;</code>
   * @return The serverTime.
   */
  long getServerTime();

  /**
   * <code>int64 revision = 10;</code>
   * @return The revision.
   */
  long getRevision();

  /**
   * <code>int64 captured_at_server_time = 11;</code>
   * @return The capturedAtServerTime.
   */
  long getCapturedAtServerTime();
}
