// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface PongPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 client_time = 1;</code>
   * @return The clientTime.
   */
  long getClientTime();

  /**
   * <code>int64 server_receive_time = 2;</code>
   * @return The serverReceiveTime.
   */
  long getServerReceiveTime();

  /**
   * <code>int64 server_send_time = 3;</code>
   * @return The serverSendTime.
   */
  long getServerSendTime();

  /**
   * <code>int64 sequence = 4;</code>
   * @return The sequence.
   */
  long getSequence();
}
