// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload}
 */
@com.google.protobuf.Generated
public  final class PongPayload extends
    com.google.protobuf.GeneratedMessageLite<
        PongPayload, PongPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload)
    PongPayloadOrBuilder {
  private PongPayload() {
  }
  public static final int CLIENT_TIME_FIELD_NUMBER = 1;
  private long clientTime_;
  /**
   * <code>int64 client_time = 1;</code>
   * @return The clientTime.
   */
  @java.lang.Override
  public long getClientTime() {
    return clientTime_;
  }
  /**
   * <code>int64 client_time = 1;</code>
   * @param value The clientTime to set.
   */
  private void setClientTime(long value) {
    
    clientTime_ = value;
  }
  /**
   * <code>int64 client_time = 1;</code>
   */
  private void clearClientTime() {

    clientTime_ = 0L;
  }

  public static final int SERVER_RECEIVE_TIME_FIELD_NUMBER = 2;
  private long serverReceiveTime_;
  /**
   * <code>int64 server_receive_time = 2;</code>
   * @return The serverReceiveTime.
   */
  @java.lang.Override
  public long getServerReceiveTime() {
    return serverReceiveTime_;
  }
  /**
   * <code>int64 server_receive_time = 2;</code>
   * @param value The serverReceiveTime to set.
   */
  private void setServerReceiveTime(long value) {
    
    serverReceiveTime_ = value;
  }
  /**
   * <code>int64 server_receive_time = 2;</code>
   */
  private void clearServerReceiveTime() {

    serverReceiveTime_ = 0L;
  }

  public static final int SERVER_SEND_TIME_FIELD_NUMBER = 3;
  private long serverSendTime_;
  /**
   * <code>int64 server_send_time = 3;</code>
   * @return The serverSendTime.
   */
  @java.lang.Override
  public long getServerSendTime() {
    return serverSendTime_;
  }
  /**
   * <code>int64 server_send_time = 3;</code>
   * @param value The serverSendTime to set.
   */
  private void setServerSendTime(long value) {
    
    serverSendTime_ = value;
  }
  /**
   * <code>int64 server_send_time = 3;</code>
   */
  private void clearServerSendTime() {

    serverSendTime_ = 0L;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 4;
  private long sequence_;
  /**
   * <code>int64 sequence = 4;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public long getSequence() {
    return sequence_;
  }
  /**
   * <code>int64 sequence = 4;</code>
   * @param value The sequence to set.
   */
  private void setSequence(long value) {
    
    sequence_ = value;
  }
  /**
   * <code>int64 sequence = 4;</code>
   */
  private void clearSequence() {

    sequence_ = 0L;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 client_time = 1;</code>
     * @return The clientTime.
     */
    @java.lang.Override
    public long getClientTime() {
      return instance.getClientTime();
    }
    /**
     * <code>int64 client_time = 1;</code>
     * @param value The clientTime to set.
     * @return This builder for chaining.
     */
    public Builder setClientTime(long value) {
      copyOnWrite();
      instance.setClientTime(value);
      return this;
    }
    /**
     * <code>int64 client_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientTime() {
      copyOnWrite();
      instance.clearClientTime();
      return this;
    }

    /**
     * <code>int64 server_receive_time = 2;</code>
     * @return The serverReceiveTime.
     */
    @java.lang.Override
    public long getServerReceiveTime() {
      return instance.getServerReceiveTime();
    }
    /**
     * <code>int64 server_receive_time = 2;</code>
     * @param value The serverReceiveTime to set.
     * @return This builder for chaining.
     */
    public Builder setServerReceiveTime(long value) {
      copyOnWrite();
      instance.setServerReceiveTime(value);
      return this;
    }
    /**
     * <code>int64 server_receive_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerReceiveTime() {
      copyOnWrite();
      instance.clearServerReceiveTime();
      return this;
    }

    /**
     * <code>int64 server_send_time = 3;</code>
     * @return The serverSendTime.
     */
    @java.lang.Override
    public long getServerSendTime() {
      return instance.getServerSendTime();
    }
    /**
     * <code>int64 server_send_time = 3;</code>
     * @param value The serverSendTime to set.
     * @return This builder for chaining.
     */
    public Builder setServerSendTime(long value) {
      copyOnWrite();
      instance.setServerSendTime(value);
      return this;
    }
    /**
     * <code>int64 server_send_time = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerSendTime() {
      copyOnWrite();
      instance.clearServerSendTime();
      return this;
    }

    /**
     * <code>int64 sequence = 4;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return instance.getSequence();
    }
    /**
     * <code>int64 sequence = 4;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(long value) {
      copyOnWrite();
      instance.setSequence(value);
      return this;
    }
    /**
     * <code>int64 sequence = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      copyOnWrite();
      instance.clearSequence();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "clientTime_",
            "serverReceiveTime_",
            "serverSendTime_",
            "sequence_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
              "\u0003\u0002\u0004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload DEFAULT_INSTANCE;
  static {
    PongPayload defaultInstance = new PongPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PongPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PongPayload> PARSER;

  public static com.google.protobuf.Parser<PongPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

