// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializepongPayload")
public inline fun pongPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload`
 */
public object PongPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload = _builder.build()

    /**
     * `int64 client_time = 1;`
     */
    public var clientTime: kotlin.Long
      @kotlin.jvm.JvmName("getClientTime")
        get() = _builder.clientTime
      @kotlin.jvm.JvmName("setClientTime")
        set(value) {
        _builder.clientTime = value
      }
    /**
     * `int64 client_time = 1;`
     */
    public fun clearClientTime() {
      _builder.clearClientTime()
    }

    /**
     * `int64 server_receive_time = 2;`
     */
    public var serverReceiveTime: kotlin.Long
      @kotlin.jvm.JvmName("getServerReceiveTime")
        get() = _builder.serverReceiveTime
      @kotlin.jvm.JvmName("setServerReceiveTime")
        set(value) {
        _builder.serverReceiveTime = value
      }
    /**
     * `int64 server_receive_time = 2;`
     */
    public fun clearServerReceiveTime() {
      _builder.clearServerReceiveTime()
    }

    /**
     * `int64 server_send_time = 3;`
     */
    public var serverSendTime: kotlin.Long
      @kotlin.jvm.JvmName("getServerSendTime")
        get() = _builder.serverSendTime
      @kotlin.jvm.JvmName("setServerSendTime")
        set(value) {
        _builder.serverSendTime = value
      }
    /**
     * `int64 server_send_time = 3;`
     */
    public fun clearServerSendTime() {
      _builder.clearServerSendTime()
    }

    /**
     * `int64 sequence = 4;`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * `int64 sequence = 4;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.PongPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.PongPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.PongPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

