// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializereconnectPayload")
public inline fun reconnectPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload`
 */
public object ReconnectPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload = _builder.build()

    /**
     * `string session_token = 1;`
     */
    public var sessionToken: kotlin.String
      @kotlin.jvm.JvmName("getSessionToken")
        get() = _builder.sessionToken
      @kotlin.jvm.JvmName("setSessionToken")
        set(value) {
        _builder.sessionToken = value
      }
    /**
     * `string session_token = 1;`
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.ReconnectPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.ReconnectPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

