// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload}
 */
@com.google.protobuf.Generated
public  final class ReconnectedPayload extends
    com.google.protobuf.GeneratedMessageLite<
        ReconnectedPayload, ReconnectedPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload)
    ReconnectedPayloadOrBuilder {
  private ReconnectedPayload() {
    roomCode_ = "";
    userId_ = "";
  }
  private int bitField0_;
  public static final int ROOM_CODE_FIELD_NUMBER = 1;
  private java.lang.String roomCode_;
  /**
   * <code>string room_code = 1;</code>
   * @return The roomCode.
   */
  @java.lang.Override
  public java.lang.String getRoomCode() {
    return roomCode_;
  }
  /**
   * <code>string room_code = 1;</code>
   * @return The bytes for roomCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roomCode_);
  }
  /**
   * <code>string room_code = 1;</code>
   * @param value The roomCode to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRoomCode(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    roomCode_ = value;
  }
  /**
   * <code>string room_code = 1;</code>
   */
  private void clearRoomCode() {

    roomCode_ = getDefaultInstance().getRoomCode();
  }
  /**
   * <code>string room_code = 1;</code>
   * @param value The bytes for roomCode to set.
   */
  private void setRoomCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    roomCode_ = value.toStringUtf8();

  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 2;</code>
   * @param value The userId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUserId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    userId_ = value;
  }
  /**
   * <code>string user_id = 2;</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 2;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 3;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   */
  @java.lang.Override
  public boolean hasState() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState getState() {
    return state_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.getDefaultInstance() : state_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setState(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState value) {
    value.getClass();  // minimal bytecode null check
    state_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeState(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState value) {
    value.getClass();  // minimal bytecode null check
    if (state_ != null &&
        state_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.getDefaultInstance()) {
      state_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.newBuilder(state_).mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   */
  private void clearState() {
    state_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int IS_HOST_FIELD_NUMBER = 4;
  private boolean isHost_;
  /**
   * <code>bool is_host = 4;</code>
   * @return The isHost.
   */
  @java.lang.Override
  public boolean getIsHost() {
    return isHost_;
  }
  /**
   * <code>bool is_host = 4;</code>
   * @param value The isHost to set.
   */
  private void setIsHost(boolean value) {
    
    isHost_ = value;
  }
  /**
   * <code>bool is_host = 4;</code>
   */
  private void clearIsHost() {

    isHost_ = false;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string room_code = 1;</code>
     * @return The roomCode.
     */
    @java.lang.Override
    public java.lang.String getRoomCode() {
      return instance.getRoomCode();
    }
    /**
     * <code>string room_code = 1;</code>
     * @return The bytes for roomCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      return instance.getRoomCodeBytes();
    }
    /**
     * <code>string room_code = 1;</code>
     * @param value The roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoomCode(value);
      return this;
    }
    /**
     * <code>string room_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomCode() {
      copyOnWrite();
      instance.clearRoomCode();
      return this;
    }
    /**
     * <code>string room_code = 1;</code>
     * @param value The bytes for roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRoomCodeBytes(value);
      return this;
    }

    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    @java.lang.Override
    public boolean hasState() {
      return instance.hasState();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState getState() {
      return instance.getState();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    public Builder setState(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    public Builder setState(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.Builder builderForValue) {
      copyOnWrite();
      instance.setState(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    public Builder mergeState(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState value) {
      copyOnWrite();
      instance.mergeState(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
     */
    public Builder clearState() {  copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>bool is_host = 4;</code>
     * @return The isHost.
     */
    @java.lang.Override
    public boolean getIsHost() {
      return instance.getIsHost();
    }
    /**
     * <code>bool is_host = 4;</code>
     * @param value The isHost to set.
     * @return This builder for chaining.
     */
    public Builder setIsHost(boolean value) {
      copyOnWrite();
      instance.setIsHost(value);
      return this;
    }
    /**
     * <code>bool is_host = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsHost() {
      copyOnWrite();
      instance.clearIsHost();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "roomCode_",
            "userId_",
            "state_",
            "isHost_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u1009\u0000\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload DEFAULT_INSTANCE;
  static {
    ReconnectedPayload defaultInstance = new ReconnectedPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ReconnectedPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ReconnectedPayload> PARSER;

  public static com.google.protobuf.Parser<ReconnectedPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

