// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface ReconnectPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string session_token = 1;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string session_token = 1;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
