// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface ReconnectedPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.ReconnectedPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string room_code = 1;</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>string room_code = 1;</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState state = 3;</code>
   * @return The state.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState getState();

  /**
   * <code>bool is_host = 4;</code>
   * @return The isHost.
   */
  boolean getIsHost();
}
