// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializerejectSuggestionPayload")
public inline fun rejectSuggestionPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload`
 */
public object RejectSuggestionPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload = _builder.build()

    /**
     * `string suggestion_id = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestion_id = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * `string reason = 2;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.RejectSuggestionPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RejectSuggestionPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.RejectSuggestionPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

