// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState}
 */
@com.google.protobuf.Generated
public  final class RoomState extends
    com.google.protobuf.GeneratedMessageLite<
        RoomState, RoomState.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState)
    RoomStateOrBuilder {
  private RoomState() {
    roomCode_ = "";
    hostId_ = "";
    users_ = emptyProtobufList();
    queue_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int ROOM_CODE_FIELD_NUMBER = 1;
  private java.lang.String roomCode_;
  /**
   * <code>string room_code = 1;</code>
   * @return The roomCode.
   */
  @java.lang.Override
  public java.lang.String getRoomCode() {
    return roomCode_;
  }
  /**
   * <code>string room_code = 1;</code>
   * @return The bytes for roomCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roomCode_);
  }
  /**
   * <code>string room_code = 1;</code>
   * @param value The roomCode to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRoomCode(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    roomCode_ = value;
  }
  /**
   * <code>string room_code = 1;</code>
   */
  private void clearRoomCode() {

    roomCode_ = getDefaultInstance().getRoomCode();
  }
  /**
   * <code>string room_code = 1;</code>
   * @param value The bytes for roomCode to set.
   */
  private void setRoomCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    roomCode_ = value.toStringUtf8();

  }

  public static final int HOST_ID_FIELD_NUMBER = 2;
  private java.lang.String hostId_;
  /**
   * <code>string host_id = 2;</code>
   * @return The hostId.
   */
  @java.lang.Override
  public java.lang.String getHostId() {
    return hostId_;
  }
  /**
   * <code>string host_id = 2;</code>
   * @return The bytes for hostId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(hostId_);
  }
  /**
   * <code>string host_id = 2;</code>
   * @param value The hostId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setHostId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    hostId_ = value;
  }
  /**
   * <code>string host_id = 2;</code>
   */
  private void clearHostId() {

    hostId_ = getDefaultInstance().getHostId();
  }
  /**
   * <code>string host_id = 2;</code>
   * @param value The bytes for hostId to set.
   */
  private void setHostIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    hostId_ = value.toStringUtf8();

  }

  public static final int USERS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> users_;
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  public java.util.List<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfoOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfoOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }
  private void ensureUsersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> tmp = users_;
    if (!tmp.isModifiable()) {
      users_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsers(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureUsersIsMutable();
    users_.set(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addUsers(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureUsersIsMutable();
    users_.add(value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addUsers(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureUsersIsMutable();
    users_.add(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  private void addAllUsers(
      java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> values) {
    ensureUsersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, users_);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  private void clearUsers() {
    users_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  private void removeUsers(int index) {
    ensureUsersIsMutable();
    users_.remove(index);
  }

  public static final int CURRENT_TRACK_FIELD_NUMBER = 4;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo currentTrack_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   */
  @java.lang.Override
  public boolean hasCurrentTrack() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack() {
    return currentTrack_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance() : currentTrack_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    currentTrack_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    if (currentTrack_ != null &&
        currentTrack_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance()) {
      currentTrack_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder(currentTrack_).mergeFrom(value).buildPartial();
    } else {
      currentTrack_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   */
  private void clearCurrentTrack() {
    currentTrack_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int IS_PLAYING_FIELD_NUMBER = 5;
  private boolean isPlaying_;
  /**
   * <code>bool is_playing = 5;</code>
   * @return The isPlaying.
   */
  @java.lang.Override
  public boolean getIsPlaying() {
    return isPlaying_;
  }
  /**
   * <code>bool is_playing = 5;</code>
   * @param value The isPlaying to set.
   */
  private void setIsPlaying(boolean value) {
    
    isPlaying_ = value;
  }
  /**
   * <code>bool is_playing = 5;</code>
   */
  private void clearIsPlaying() {

    isPlaying_ = false;
  }

  public static final int POSITION_FIELD_NUMBER = 6;
  private long position_;
  /**
   * <code>int64 position = 6;</code>
   * @return The position.
   */
  @java.lang.Override
  public long getPosition() {
    return position_;
  }
  /**
   * <code>int64 position = 6;</code>
   * @param value The position to set.
   */
  private void setPosition(long value) {
    
    position_ = value;
  }
  /**
   * <code>int64 position = 6;</code>
   */
  private void clearPosition() {

    position_ = 0L;
  }

  public static final int LAST_UPDATE_FIELD_NUMBER = 7;
  private long lastUpdate_;
  /**
   * <code>int64 last_update = 7;</code>
   * @return The lastUpdate.
   */
  @java.lang.Override
  public long getLastUpdate() {
    return lastUpdate_;
  }
  /**
   * <code>int64 last_update = 7;</code>
   * @param value The lastUpdate to set.
   */
  private void setLastUpdate(long value) {
    
    lastUpdate_ = value;
  }
  /**
   * <code>int64 last_update = 7;</code>
   */
  private void clearLastUpdate() {

    lastUpdate_ = 0L;
  }

  public static final int VOLUME_FIELD_NUMBER = 8;
  private float volume_;
  /**
   * <code>float volume = 8;</code>
   * @return The volume.
   */
  @java.lang.Override
  public float getVolume() {
    return volume_;
  }
  /**
   * <code>float volume = 8;</code>
   * @param value The volume to set.
   */
  private void setVolume(float value) {
    
    volume_ = value;
  }
  /**
   * <code>float volume = 8;</code>
   */
  private void clearVolume() {

    volume_ = 0F;
  }

  public static final int QUEUE_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> queue_;
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.Override
  public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  public java.util.List<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder> 
      getQueueOrBuilderList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.Override
  public int getQueueCount() {
    return queue_.size();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
    return queue_.get(index);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder getQueueOrBuilder(
      int index) {
    return queue_.get(index);
  }
  private void ensureQueueIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> tmp = queue_;
    if (!tmp.isModifiable()) {
      queue_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.set(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  private void addAllQueue(
      java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
    ensureQueueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, queue_);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  private void clearQueue() {
    queue_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  private void removeQueue(int index) {
    ensureQueueIsMutable();
    queue_.remove(index);
  }

  public static final int REVISION_FIELD_NUMBER = 10;
  private long revision_;
  /**
   * <code>int64 revision = 10;</code>
   * @return The revision.
   */
  @java.lang.Override
  public long getRevision() {
    return revision_;
  }
  /**
   * <code>int64 revision = 10;</code>
   * @param value The revision to set.
   */
  private void setRevision(long value) {
    
    revision_ = value;
  }
  /**
   * <code>int64 revision = 10;</code>
   */
  private void clearRevision() {

    revision_ = 0L;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomStateOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string room_code = 1;</code>
     * @return The roomCode.
     */
    @java.lang.Override
    public java.lang.String getRoomCode() {
      return instance.getRoomCode();
    }
    /**
     * <code>string room_code = 1;</code>
     * @return The bytes for roomCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      return instance.getRoomCodeBytes();
    }
    /**
     * <code>string room_code = 1;</code>
     * @param value The roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoomCode(value);
      return this;
    }
    /**
     * <code>string room_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomCode() {
      copyOnWrite();
      instance.clearRoomCode();
      return this;
    }
    /**
     * <code>string room_code = 1;</code>
     * @param value The bytes for roomCode to set.
     * @return This builder for chaining.
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRoomCodeBytes(value);
      return this;
    }

    /**
     * <code>string host_id = 2;</code>
     * @return The hostId.
     */
    @java.lang.Override
    public java.lang.String getHostId() {
      return instance.getHostId();
    }
    /**
     * <code>string host_id = 2;</code>
     * @return The bytes for hostId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostIdBytes() {
      return instance.getHostIdBytes();
    }
    /**
     * <code>string host_id = 2;</code>
     * @param value The hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostId(
        java.lang.String value) {
      copyOnWrite();
      instance.setHostId(value);
      return this;
    }
    /**
     * <code>string host_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostId() {
      copyOnWrite();
      instance.clearHostId();
      return this;
    }
    /**
     * <code>string host_id = 2;</code>
     * @param value The bytes for hostId to set.
     * @return This builder for chaining.
     */
    public Builder setHostIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHostIdBytes(value);
      return this;
    }

    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> getUsersList() {
      return java.util.Collections.unmodifiableList(
          instance.getUsersList());
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return instance.getUsersCount();
    }/**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo getUsers(int index) {
      return instance.getUsers(index);
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder setUsers(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
      copyOnWrite();
      instance.setUsers(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder setUsers(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder addUsers(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
      copyOnWrite();
      instance.addUsers(value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder addUsers(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo value) {
      copyOnWrite();
      instance.addUsers(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder addUsers(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addUsers(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder addUsers(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> values) {
      copyOnWrite();
      instance.addAllUsers(values);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder clearUsers() {
      copyOnWrite();
      instance.clearUsers();
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
     */
    public Builder removeUsers(int index) {
      copyOnWrite();
      instance.removeUsers(index);
      return this;
    }

    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    @java.lang.Override
    public boolean hasCurrentTrack() {
      return instance.hasCurrentTrack();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack() {
      return instance.getCurrentTrack();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    public Builder setCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setCurrentTrack(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    public Builder setCurrentTrack(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setCurrentTrack(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    public Builder mergeCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.mergeCurrentTrack(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
     */
    public Builder clearCurrentTrack() {  copyOnWrite();
      instance.clearCurrentTrack();
      return this;
    }

    /**
     * <code>bool is_playing = 5;</code>
     * @return The isPlaying.
     */
    @java.lang.Override
    public boolean getIsPlaying() {
      return instance.getIsPlaying();
    }
    /**
     * <code>bool is_playing = 5;</code>
     * @param value The isPlaying to set.
     * @return This builder for chaining.
     */
    public Builder setIsPlaying(boolean value) {
      copyOnWrite();
      instance.setIsPlaying(value);
      return this;
    }
    /**
     * <code>bool is_playing = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPlaying() {
      copyOnWrite();
      instance.clearIsPlaying();
      return this;
    }

    /**
     * <code>int64 position = 6;</code>
     * @return The position.
     */
    @java.lang.Override
    public long getPosition() {
      return instance.getPosition();
    }
    /**
     * <code>int64 position = 6;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(long value) {
      copyOnWrite();
      instance.setPosition(value);
      return this;
    }
    /**
     * <code>int64 position = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      copyOnWrite();
      instance.clearPosition();
      return this;
    }

    /**
     * <code>int64 last_update = 7;</code>
     * @return The lastUpdate.
     */
    @java.lang.Override
    public long getLastUpdate() {
      return instance.getLastUpdate();
    }
    /**
     * <code>int64 last_update = 7;</code>
     * @param value The lastUpdate to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdate(long value) {
      copyOnWrite();
      instance.setLastUpdate(value);
      return this;
    }
    /**
     * <code>int64 last_update = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdate() {
      copyOnWrite();
      instance.clearLastUpdate();
      return this;
    }

    /**
     * <code>float volume = 8;</code>
     * @return The volume.
     */
    @java.lang.Override
    public float getVolume() {
      return instance.getVolume();
    }
    /**
     * <code>float volume = 8;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(float value) {
      copyOnWrite();
      instance.setVolume(value);
      return this;
    }
    /**
     * <code>float volume = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      copyOnWrite();
      instance.clearVolume();
      return this;
    }

    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    @java.lang.Override
    public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
      return java.util.Collections.unmodifiableList(
          instance.getQueueList());
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    @java.lang.Override
    public int getQueueCount() {
      return instance.getQueueCount();
    }/**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
      return instance.getQueue(index);
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder addQueue(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder addAllQueue(
        java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
      copyOnWrite();
      instance.addAllQueue(values);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder clearQueue() {
      copyOnWrite();
      instance.clearQueue();
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
     */
    public Builder removeQueue(int index) {
      copyOnWrite();
      instance.removeQueue(index);
      return this;
    }

    /**
     * <code>int64 revision = 10;</code>
     * @return The revision.
     */
    @java.lang.Override
    public long getRevision() {
      return instance.getRevision();
    }
    /**
     * <code>int64 revision = 10;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(long value) {
      copyOnWrite();
      instance.setRevision(value);
      return this;
    }
    /**
     * <code>int64 revision = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      copyOnWrite();
      instance.clearRevision();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "roomCode_",
            "hostId_",
            "users_",
            com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo.class,
            "currentTrack_",
            "isPlaying_",
            "position_",
            "lastUpdate_",
            "volume_",
            "queue_",
            com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.class,
            "revision_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0001\u0001\n\n\u0000\u0002\u0000\u0001\u0208\u0002\u0208\u0003\u001b" +
              "\u0004\u1009\u0000\u0005\u0007\u0006\u0002\u0007\u0002\b\u0001\t\u001b\n\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState DEFAULT_INSTANCE;
  static {
    RoomState defaultInstance = new RoomState();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RoomState.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RoomState> PARSER;

  public static com.google.protobuf.Parser<RoomState> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

