// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface RoomStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.RoomState)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string room_code = 1;</code>
   * @return The roomCode.
   */
  java.lang.String getRoomCode();
  /**
   * <code>string room_code = 1;</code>
   * @return The bytes for roomCode.
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <code>string host_id = 2;</code>
   * @return The hostId.
   */
  java.lang.String getHostId();
  /**
   * <code>string host_id = 2;</code>
   * @return The bytes for hostId.
   */
  com.google.protobuf.ByteString
      getHostIdBytes();

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo> 
      getUsersList();
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo getUsers(int index);
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.UserInfo users = 3;</code>
   */
  int getUsersCount();

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   * @return Whether the currentTrack field is set.
   */
  boolean hasCurrentTrack();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 4;</code>
   * @return The currentTrack.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack();

  /**
   * <code>bool is_playing = 5;</code>
   * @return The isPlaying.
   */
  boolean getIsPlaying();

  /**
   * <code>int64 position = 6;</code>
   * @return The position.
   */
  long getPosition();

  /**
   * <code>int64 last_update = 7;</code>
   * @return The lastUpdate.
   */
  long getLastUpdate();

  /**
   * <code>float volume = 8;</code>
   * @return The volume.
   */
  float getVolume();

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> 
      getQueueList();
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index);
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 9;</code>
   */
  int getQueueCount();

  /**
   * <code>int64 revision = 10;</code>
   * @return The revision.
   */
  long getRevision();
}
