// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializesuggestTrackPayload")
public inline fun suggestTrackPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload`
 */
public object SuggestTrackPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload = _builder.build()

    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;`
     */
    public var trackInfo: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo
      @kotlin.jvm.JvmName("getTrackInfo")
        get() = _builder.trackInfo
      @kotlin.jvm.JvmName("setTrackInfo")
        set(value) {
        _builder.trackInfo = value
      }
    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;`
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;`
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    public val SuggestTrackPayloadKt.Dsl.trackInfoOrNull: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo?
      get() = _builder.trackInfoOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.SuggestTrackPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.SuggestTrackPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayloadOrBuilder.trackInfoOrNull: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

