// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface SuggestTrackPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   * @return Whether the trackInfo field is set.
   */
  boolean hasTrackInfo();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   * @return The trackInfo.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo();
}
