// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload}
 */
@com.google.protobuf.Generated
public  final class SuggestTrackPayload extends
    com.google.protobuf.GeneratedMessageLite<
        SuggestTrackPayload, SuggestTrackPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload)
    SuggestTrackPayloadOrBuilder {
  private SuggestTrackPayload() {
  }
  private int bitField0_;
  public static final int TRACK_INFO_FIELD_NUMBER = 1;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo trackInfo_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   */
  @java.lang.Override
  public boolean hasTrackInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
    return trackInfo_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance() : trackInfo_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    trackInfo_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    if (trackInfo_ != null &&
        trackInfo_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance()) {
      trackInfo_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder(trackInfo_).mergeFrom(value).buildPartial();
    } else {
      trackInfo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
   */
  private void clearTrackInfo() {
    trackInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    @java.lang.Override
    public boolean hasTrackInfo() {
      return instance.hasTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
      return instance.getTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    public Builder setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setTrackInfo(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    public Builder setTrackInfo(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setTrackInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    public Builder mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.mergeTrackInfo(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 1;</code>
     */
    public Builder clearTrackInfo() {  copyOnWrite();
      instance.clearTrackInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "trackInfo_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload DEFAULT_INSTANCE;
  static {
    SuggestTrackPayload defaultInstance = new SuggestTrackPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SuggestTrackPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestTrackPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SuggestTrackPayload> PARSER;

  public static com.google.protobuf.Parser<SuggestTrackPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

