// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface SuggestionReceivedPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string suggestion_id = 1;</code>
   * @return The suggestionId.
   */
  java.lang.String getSuggestionId();
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The bytes for suggestionId.
   */
  com.google.protobuf.ByteString
      getSuggestionIdBytes();

  /**
   * <code>string from_user_id = 2;</code>
   * @return The fromUserId.
   */
  java.lang.String getFromUserId();
  /**
   * <code>string from_user_id = 2;</code>
   * @return The bytes for fromUserId.
   */
  com.google.protobuf.ByteString
      getFromUserIdBytes();

  /**
   * <code>string from_username = 3;</code>
   * @return The fromUsername.
   */
  java.lang.String getFromUsername();
  /**
   * <code>string from_username = 3;</code>
   * @return The bytes for fromUsername.
   */
  com.google.protobuf.ByteString
      getFromUsernameBytes();

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   * @return Whether the trackInfo field is set.
   */
  boolean hasTrackInfo();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   * @return The trackInfo.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo();
}
