// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload}
 */
@com.google.protobuf.Generated
public  final class SuggestionReceivedPayload extends
    com.google.protobuf.GeneratedMessageLite<
        SuggestionReceivedPayload, SuggestionReceivedPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload)
    SuggestionReceivedPayloadOrBuilder {
  private SuggestionReceivedPayload() {
    suggestionId_ = "";
    fromUserId_ = "";
    fromUsername_ = "";
  }
  private int bitField0_;
  public static final int SUGGESTION_ID_FIELD_NUMBER = 1;
  private java.lang.String suggestionId_;
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The suggestionId.
   */
  @java.lang.Override
  public java.lang.String getSuggestionId() {
    return suggestionId_;
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The bytes for suggestionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuggestionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(suggestionId_);
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @param value The suggestionId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSuggestionId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    suggestionId_ = value;
  }
  /**
   * <code>string suggestion_id = 1;</code>
   */
  private void clearSuggestionId() {

    suggestionId_ = getDefaultInstance().getSuggestionId();
  }
  /**
   * <code>string suggestion_id = 1;</code>
   * @param value The bytes for suggestionId to set.
   */
  private void setSuggestionIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    suggestionId_ = value.toStringUtf8();

  }

  public static final int FROM_USER_ID_FIELD_NUMBER = 2;
  private java.lang.String fromUserId_;
  /**
   * <code>string from_user_id = 2;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public java.lang.String getFromUserId() {
    return fromUserId_;
  }
  /**
   * <code>string from_user_id = 2;</code>
   * @return The bytes for fromUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fromUserId_);
  }
  /**
   * <code>string from_user_id = 2;</code>
   * @param value The fromUserId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setFromUserId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    fromUserId_ = value;
  }
  /**
   * <code>string from_user_id = 2;</code>
   */
  private void clearFromUserId() {

    fromUserId_ = getDefaultInstance().getFromUserId();
  }
  /**
   * <code>string from_user_id = 2;</code>
   * @param value The bytes for fromUserId to set.
   */
  private void setFromUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    fromUserId_ = value.toStringUtf8();

  }

  public static final int FROM_USERNAME_FIELD_NUMBER = 3;
  private java.lang.String fromUsername_;
  /**
   * <code>string from_username = 3;</code>
   * @return The fromUsername.
   */
  @java.lang.Override
  public java.lang.String getFromUsername() {
    return fromUsername_;
  }
  /**
   * <code>string from_username = 3;</code>
   * @return The bytes for fromUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fromUsername_);
  }
  /**
   * <code>string from_username = 3;</code>
   * @param value The fromUsername to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setFromUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    fromUsername_ = value;
  }
  /**
   * <code>string from_username = 3;</code>
   */
  private void clearFromUsername() {

    fromUsername_ = getDefaultInstance().getFromUsername();
  }
  /**
   * <code>string from_username = 3;</code>
   * @param value The bytes for fromUsername to set.
   */
  private void setFromUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    fromUsername_ = value.toStringUtf8();

  }

  public static final int TRACK_INFO_FIELD_NUMBER = 4;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo trackInfo_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.Override
  public boolean hasTrackInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
    return trackInfo_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance() : trackInfo_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    trackInfo_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    if (trackInfo_ != null &&
        trackInfo_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance()) {
      trackInfo_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder(trackInfo_).mergeFrom(value).buildPartial();
    } else {
      trackInfo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
   */
  private void clearTrackInfo() {
    trackInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string suggestion_id = 1;</code>
     * @return The suggestionId.
     */
    @java.lang.Override
    public java.lang.String getSuggestionId() {
      return instance.getSuggestionId();
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @return The bytes for suggestionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSuggestionIdBytes() {
      return instance.getSuggestionIdBytes();
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @param value The suggestionId to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSuggestionId(value);
      return this;
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuggestionId() {
      copyOnWrite();
      instance.clearSuggestionId();
      return this;
    }
    /**
     * <code>string suggestion_id = 1;</code>
     * @param value The bytes for suggestionId to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSuggestionIdBytes(value);
      return this;
    }

    /**
     * <code>string from_user_id = 2;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public java.lang.String getFromUserId() {
      return instance.getFromUserId();
    }
    /**
     * <code>string from_user_id = 2;</code>
     * @return The bytes for fromUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      return instance.getFromUserIdBytes();
    }
    /**
     * <code>string from_user_id = 2;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setFromUserId(value);
      return this;
    }
    /**
     * <code>string from_user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      copyOnWrite();
      instance.clearFromUserId();
      return this;
    }
    /**
     * <code>string from_user_id = 2;</code>
     * @param value The bytes for fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFromUserIdBytes(value);
      return this;
    }

    /**
     * <code>string from_username = 3;</code>
     * @return The fromUsername.
     */
    @java.lang.Override
    public java.lang.String getFromUsername() {
      return instance.getFromUsername();
    }
    /**
     * <code>string from_username = 3;</code>
     * @return The bytes for fromUsername.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromUsernameBytes() {
      return instance.getFromUsernameBytes();
    }
    /**
     * <code>string from_username = 3;</code>
     * @param value The fromUsername to set.
     * @return This builder for chaining.
     */
    public Builder setFromUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setFromUsername(value);
      return this;
    }
    /**
     * <code>string from_username = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUsername() {
      copyOnWrite();
      instance.clearFromUsername();
      return this;
    }
    /**
     * <code>string from_username = 3;</code>
     * @param value The bytes for fromUsername to set.
     * @return This builder for chaining.
     */
    public Builder setFromUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFromUsernameBytes(value);
      return this;
    }

    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    @java.lang.Override
    public boolean hasTrackInfo() {
      return instance.hasTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo() {
      return instance.getTrackInfo();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder setTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setTrackInfo(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder setTrackInfo(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setTrackInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder mergeTrackInfo(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.mergeTrackInfo(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 4;</code>
     */
    public Builder clearTrackInfo() {  copyOnWrite();
      instance.clearTrackInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "suggestionId_",
            "fromUserId_",
            "fromUsername_",
            "trackInfo_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload DEFAULT_INSTANCE;
  static {
    SuggestionReceivedPayload defaultInstance = new SuggestionReceivedPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SuggestionReceivedPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionReceivedPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SuggestionReceivedPayload> PARSER;

  public static com.google.protobuf.Parser<SuggestionReceivedPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

