// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializesuggestionApprovedPayload")
public inline fun suggestionApprovedPayload(block: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload =
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayloadKt.Dsl._create(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload`
 */
public object SuggestionApprovedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload = _builder.build()

    /**
     * `string suggestion_id = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestion_id = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 2;`
     */
    public var trackInfo: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo
      @kotlin.jvm.JvmName("getTrackInfo")
        get() = _builder.trackInfo
      @kotlin.jvm.JvmName("setTrackInfo")
        set(value) {
        _builder.trackInfo = value
      }
    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 2;`
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * `.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 2;`
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    public val SuggestionApprovedPayloadKt.Dsl.trackInfoOrNull: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo?
      get() = _builder.trackInfoOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload.copy(block: `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload =
  `com.mohsinraza.mohsinapexmusic.music.listentogether.proto`.SuggestionApprovedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayloadOrBuilder.trackInfoOrNull: com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

