// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface SuggestionApprovedPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SuggestionApprovedPayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string suggestion_id = 1;</code>
   * @return The suggestionId.
   */
  java.lang.String getSuggestionId();
  /**
   * <code>string suggestion_id = 1;</code>
   * @return The bytes for suggestionId.
   */
  com.google.protobuf.ByteString
      getSuggestionIdBytes();

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 2;</code>
   * @return Whether the trackInfo field is set.
   */
  boolean hasTrackInfo();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo track_info = 2;</code>
   * @return The trackInfo.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getTrackInfo();
}
