// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload}
 */
@com.google.protobuf.Generated
public  final class SyncStatePayload extends
    com.google.protobuf.GeneratedMessageLite<
        SyncStatePayload, SyncStatePayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload)
    SyncStatePayloadOrBuilder {
  private SyncStatePayload() {
    queue_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int CURRENT_TRACK_FIELD_NUMBER = 1;
  private com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo currentTrack_;
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   */
  @java.lang.Override
  public boolean hasCurrentTrack() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack() {
    return currentTrack_ == null ? com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance() : currentTrack_;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    currentTrack_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    if (currentTrack_ != null &&
        currentTrack_ != com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.getDefaultInstance()) {
      currentTrack_ =
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder(currentTrack_).mergeFrom(value).buildPartial();
    } else {
      currentTrack_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   */
  private void clearCurrentTrack() {
    currentTrack_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int IS_PLAYING_FIELD_NUMBER = 2;
  private boolean isPlaying_;
  /**
   * <code>bool is_playing = 2;</code>
   * @return The isPlaying.
   */
  @java.lang.Override
  public boolean getIsPlaying() {
    return isPlaying_;
  }
  /**
   * <code>bool is_playing = 2;</code>
   * @param value The isPlaying to set.
   */
  private void setIsPlaying(boolean value) {
    
    isPlaying_ = value;
  }
  /**
   * <code>bool is_playing = 2;</code>
   */
  private void clearIsPlaying() {

    isPlaying_ = false;
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private long position_;
  /**
   * <code>int64 position = 3;</code>
   * @return The position.
   */
  @java.lang.Override
  public long getPosition() {
    return position_;
  }
  /**
   * <code>int64 position = 3;</code>
   * @param value The position to set.
   */
  private void setPosition(long value) {
    
    position_ = value;
  }
  /**
   * <code>int64 position = 3;</code>
   */
  private void clearPosition() {

    position_ = 0L;
  }

  public static final int LAST_UPDATE_FIELD_NUMBER = 4;
  private long lastUpdate_;
  /**
   * <code>int64 last_update = 4;</code>
   * @return The lastUpdate.
   */
  @java.lang.Override
  public long getLastUpdate() {
    return lastUpdate_;
  }
  /**
   * <code>int64 last_update = 4;</code>
   * @param value The lastUpdate to set.
   */
  private void setLastUpdate(long value) {
    
    lastUpdate_ = value;
  }
  /**
   * <code>int64 last_update = 4;</code>
   */
  private void clearLastUpdate() {

    lastUpdate_ = 0L;
  }

  public static final int QUEUE_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> queue_;
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  public java.util.List<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder> 
      getQueueOrBuilderList() {
    return queue_;
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.Override
  public int getQueueCount() {
    return queue_.size();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.Override
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
    return queue_.get(index);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder getQueueOrBuilder(
      int index) {
    return queue_.get(index);
  }
  private void ensureQueueIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> tmp = queue_;
    if (!tmp.isModifiable()) {
      queue_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.set(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addQueue(
      int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
    value.getClass();  // minimal bytecode null check
    ensureQueueIsMutable();
    queue_.add(index, value);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  private void addAllQueue(
      java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
    ensureQueueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, queue_);
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  private void clearQueue() {
    queue_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  private void removeQueue(int index) {
    ensureQueueIsMutable();
    queue_.remove(index);
  }

  public static final int VOLUME_FIELD_NUMBER = 6;
  private float volume_;
  /**
   * <code>float volume = 6;</code>
   * @return The volume.
   */
  @java.lang.Override
  public float getVolume() {
    return volume_;
  }
  /**
   * <code>float volume = 6;</code>
   * @param value The volume to set.
   */
  private void setVolume(float value) {
    
    volume_ = value;
  }
  /**
   * <code>float volume = 6;</code>
   */
  private void clearVolume() {

    volume_ = 0F;
  }

  public static final int REVISION_FIELD_NUMBER = 7;
  private long revision_;
  /**
   * <code>int64 revision = 7;</code>
   * @return The revision.
   */
  @java.lang.Override
  public long getRevision() {
    return revision_;
  }
  /**
   * <code>int64 revision = 7;</code>
   * @param value The revision to set.
   */
  private void setRevision(long value) {
    
    revision_ = value;
  }
  /**
   * <code>int64 revision = 7;</code>
   */
  private void clearRevision() {

    revision_ = 0L;
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    @java.lang.Override
    public boolean hasCurrentTrack() {
      return instance.hasCurrentTrack();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack() {
      return instance.getCurrentTrack();
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    public Builder setCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setCurrentTrack(value);
      return this;
      }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    public Builder setCurrentTrack(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setCurrentTrack(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    public Builder mergeCurrentTrack(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.mergeCurrentTrack(value);
      return this;
    }
    /**
     * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
     */
    public Builder clearCurrentTrack() {  copyOnWrite();
      instance.clearCurrentTrack();
      return this;
    }

    /**
     * <code>bool is_playing = 2;</code>
     * @return The isPlaying.
     */
    @java.lang.Override
    public boolean getIsPlaying() {
      return instance.getIsPlaying();
    }
    /**
     * <code>bool is_playing = 2;</code>
     * @param value The isPlaying to set.
     * @return This builder for chaining.
     */
    public Builder setIsPlaying(boolean value) {
      copyOnWrite();
      instance.setIsPlaying(value);
      return this;
    }
    /**
     * <code>bool is_playing = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPlaying() {
      copyOnWrite();
      instance.clearIsPlaying();
      return this;
    }

    /**
     * <code>int64 position = 3;</code>
     * @return The position.
     */
    @java.lang.Override
    public long getPosition() {
      return instance.getPosition();
    }
    /**
     * <code>int64 position = 3;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(long value) {
      copyOnWrite();
      instance.setPosition(value);
      return this;
    }
    /**
     * <code>int64 position = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      copyOnWrite();
      instance.clearPosition();
      return this;
    }

    /**
     * <code>int64 last_update = 4;</code>
     * @return The lastUpdate.
     */
    @java.lang.Override
    public long getLastUpdate() {
      return instance.getLastUpdate();
    }
    /**
     * <code>int64 last_update = 4;</code>
     * @param value The lastUpdate to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdate(long value) {
      copyOnWrite();
      instance.setLastUpdate(value);
      return this;
    }
    /**
     * <code>int64 last_update = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdate() {
      copyOnWrite();
      instance.clearLastUpdate();
      return this;
    }

    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> getQueueList() {
      return java.util.Collections.unmodifiableList(
          instance.getQueueList());
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    @java.lang.Override
    public int getQueueCount() {
      return instance.getQueueCount();
    }/**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    @java.lang.Override
    public com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index) {
      return instance.getQueue(index);
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.setQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder setQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder addQueue(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo value) {
      copyOnWrite();
      instance.addQueue(index, value);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder addQueue(
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder addQueue(
        int index, com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addQueue(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder addAllQueue(
        java.lang.Iterable<? extends com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> values) {
      copyOnWrite();
      instance.addAllQueue(values);
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder clearQueue() {
      copyOnWrite();
      instance.clearQueue();
      return this;
    }
    /**
     * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
     */
    public Builder removeQueue(int index) {
      copyOnWrite();
      instance.removeQueue(index);
      return this;
    }

    /**
     * <code>float volume = 6;</code>
     * @return The volume.
     */
    @java.lang.Override
    public float getVolume() {
      return instance.getVolume();
    }
    /**
     * <code>float volume = 6;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(float value) {
      copyOnWrite();
      instance.setVolume(value);
      return this;
    }
    /**
     * <code>float volume = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      copyOnWrite();
      instance.clearVolume();
      return this;
    }

    /**
     * <code>int64 revision = 7;</code>
     * @return The revision.
     */
    @java.lang.Override
    public long getRevision() {
      return instance.getRevision();
    }
    /**
     * <code>int64 revision = 7;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(long value) {
      copyOnWrite();
      instance.setRevision(value);
      return this;
    }
    /**
     * <code>int64 revision = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      copyOnWrite();
      instance.clearRevision();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "currentTrack_",
            "isPlaying_",
            "position_",
            "lastUpdate_",
            "queue_",
            com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.class,
            "volume_",
            "revision_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0001\u0000\u0001\u1009\u0000\u0002" +
              "\u0007\u0003\u0002\u0004\u0002\u0005\u001b\u0006\u0001\u0007\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload DEFAULT_INSTANCE;
  static {
    SyncStatePayload defaultInstance = new SyncStatePayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SyncStatePayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SyncStatePayload> PARSER;

  public static com.google.protobuf.Parser<SyncStatePayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

