// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface SyncStatePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.SyncStatePayload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   * @return Whether the currentTrack field is set.
   */
  boolean hasCurrentTrack();
  /**
   * <code>.com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo current_track = 1;</code>
   * @return The currentTrack.
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getCurrentTrack();

  /**
   * <code>bool is_playing = 2;</code>
   * @return The isPlaying.
   */
  boolean getIsPlaying();

  /**
   * <code>int64 position = 3;</code>
   * @return The position.
   */
  long getPosition();

  /**
   * <code>int64 last_update = 4;</code>
   * @return The lastUpdate.
   */
  long getLastUpdate();

  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  java.util.List<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> 
      getQueueList();
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getQueue(int index);
  /**
   * <code>repeated .com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo queue = 5;</code>
   */
  int getQueueCount();

  /**
   * <code>float volume = 6;</code>
   * @return The volume.
   */
  float getVolume();

  /**
   * <code>int64 revision = 7;</code>
   * @return The revision.
   */
  long getRevision();
}
