// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

@com.google.protobuf.Generated
public interface TrackInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string artist = 3;</code>
   * @return The artist.
   */
  java.lang.String getArtist();
  /**
   * <code>string artist = 3;</code>
   * @return The bytes for artist.
   */
  com.google.protobuf.ByteString
      getArtistBytes();

  /**
   * <code>string album = 4;</code>
   * @return The album.
   */
  java.lang.String getAlbum();
  /**
   * <code>string album = 4;</code>
   * @return The bytes for album.
   */
  com.google.protobuf.ByteString
      getAlbumBytes();

  /**
   * <code>int64 duration = 5;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>string thumbnail = 6;</code>
   * @return The thumbnail.
   */
  java.lang.String getThumbnail();
  /**
   * <code>string thumbnail = 6;</code>
   * @return The bytes for thumbnail.
   */
  com.google.protobuf.ByteString
      getThumbnailBytes();

  /**
   * <code>string suggested_by = 7;</code>
   * @return The suggestedBy.
   */
  java.lang.String getSuggestedBy();
  /**
   * <code>string suggested_by = 7;</code>
   * @return The bytes for suggestedBy.
   */
  com.google.protobuf.ByteString
      getSuggestedByBytes();
}
