// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo}
 */
@com.google.protobuf.Generated
public  final class TrackInfo extends
    com.google.protobuf.GeneratedMessageLite<
        TrackInfo, TrackInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo)
    TrackInfoOrBuilder {
  private TrackInfo() {
    id_ = "";
    title_ = "";
    artist_ = "";
    album_ = "";
    thumbnail_ = "";
    suggestedBy_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    id_ = value;
  }
  /**
   * <code>string id = 1;</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 2;</code>
   * @param value The title to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTitle(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    title_ = value;
  }
  /**
   * <code>string title = 2;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 2;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int ARTIST_FIELD_NUMBER = 3;
  private java.lang.String artist_;
  /**
   * <code>string artist = 3;</code>
   * @return The artist.
   */
  @java.lang.Override
  public java.lang.String getArtist() {
    return artist_;
  }
  /**
   * <code>string artist = 3;</code>
   * @return The bytes for artist.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArtistBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(artist_);
  }
  /**
   * <code>string artist = 3;</code>
   * @param value The artist to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setArtist(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    artist_ = value;
  }
  /**
   * <code>string artist = 3;</code>
   */
  private void clearArtist() {

    artist_ = getDefaultInstance().getArtist();
  }
  /**
   * <code>string artist = 3;</code>
   * @param value The bytes for artist to set.
   */
  private void setArtistBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    artist_ = value.toStringUtf8();

  }

  public static final int ALBUM_FIELD_NUMBER = 4;
  private java.lang.String album_;
  /**
   * <code>string album = 4;</code>
   * @return The album.
   */
  @java.lang.Override
  public java.lang.String getAlbum() {
    return album_;
  }
  /**
   * <code>string album = 4;</code>
   * @return The bytes for album.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(album_);
  }
  /**
   * <code>string album = 4;</code>
   * @param value The album to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAlbum(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    album_ = value;
  }
  /**
   * <code>string album = 4;</code>
   */
  private void clearAlbum() {

    album_ = getDefaultInstance().getAlbum();
  }
  /**
   * <code>string album = 4;</code>
   * @param value The bytes for album to set.
   */
  private void setAlbumBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    album_ = value.toStringUtf8();

  }

  public static final int DURATION_FIELD_NUMBER = 5;
  private long duration_;
  /**
   * <code>int64 duration = 5;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }
  /**
   * <code>int64 duration = 5;</code>
   * @param value The duration to set.
   */
  private void setDuration(long value) {
    
    duration_ = value;
  }
  /**
   * <code>int64 duration = 5;</code>
   */
  private void clearDuration() {

    duration_ = 0L;
  }

  public static final int THUMBNAIL_FIELD_NUMBER = 6;
  private java.lang.String thumbnail_;
  /**
   * <code>string thumbnail = 6;</code>
   * @return The thumbnail.
   */
  @java.lang.Override
  public java.lang.String getThumbnail() {
    return thumbnail_;
  }
  /**
   * <code>string thumbnail = 6;</code>
   * @return The bytes for thumbnail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThumbnailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(thumbnail_);
  }
  /**
   * <code>string thumbnail = 6;</code>
   * @param value The thumbnail to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setThumbnail(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    thumbnail_ = value;
  }
  /**
   * <code>string thumbnail = 6;</code>
   */
  private void clearThumbnail() {

    thumbnail_ = getDefaultInstance().getThumbnail();
  }
  /**
   * <code>string thumbnail = 6;</code>
   * @param value The bytes for thumbnail to set.
   */
  private void setThumbnailBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    thumbnail_ = value.toStringUtf8();

  }

  public static final int SUGGESTED_BY_FIELD_NUMBER = 7;
  private java.lang.String suggestedBy_;
  /**
   * <code>string suggested_by = 7;</code>
   * @return The suggestedBy.
   */
  @java.lang.Override
  public java.lang.String getSuggestedBy() {
    return suggestedBy_;
  }
  /**
   * <code>string suggested_by = 7;</code>
   * @return The bytes for suggestedBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuggestedByBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(suggestedBy_);
  }
  /**
   * <code>string suggested_by = 7;</code>
   * @param value The suggestedBy to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSuggestedBy(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    suggestedBy_ = value;
  }
  /**
   * <code>string suggested_by = 7;</code>
   */
  private void clearSuggestedBy() {

    suggestedBy_ = getDefaultInstance().getSuggestedBy();
  }
  /**
   * <code>string suggested_by = 7;</code>
   * @param value The bytes for suggestedBy to set.
   */
  private void setSuggestedByBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    suggestedBy_ = value.toStringUtf8();

  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfoOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string artist = 3;</code>
     * @return The artist.
     */
    @java.lang.Override
    public java.lang.String getArtist() {
      return instance.getArtist();
    }
    /**
     * <code>string artist = 3;</code>
     * @return The bytes for artist.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArtistBytes() {
      return instance.getArtistBytes();
    }
    /**
     * <code>string artist = 3;</code>
     * @param value The artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtist(
        java.lang.String value) {
      copyOnWrite();
      instance.setArtist(value);
      return this;
    }
    /**
     * <code>string artist = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtist() {
      copyOnWrite();
      instance.clearArtist();
      return this;
    }
    /**
     * <code>string artist = 3;</code>
     * @param value The bytes for artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtistBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setArtistBytes(value);
      return this;
    }

    /**
     * <code>string album = 4;</code>
     * @return The album.
     */
    @java.lang.Override
    public java.lang.String getAlbum() {
      return instance.getAlbum();
    }
    /**
     * <code>string album = 4;</code>
     * @return The bytes for album.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      return instance.getAlbumBytes();
    }
    /**
     * <code>string album = 4;</code>
     * @param value The album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbum(
        java.lang.String value) {
      copyOnWrite();
      instance.setAlbum(value);
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbum() {
      copyOnWrite();
      instance.clearAlbum();
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @param value The bytes for album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAlbumBytes(value);
      return this;
    }

    /**
     * <code>int64 duration = 5;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>int64 duration = 5;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>int64 duration = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <code>string thumbnail = 6;</code>
     * @return The thumbnail.
     */
    @java.lang.Override
    public java.lang.String getThumbnail() {
      return instance.getThumbnail();
    }
    /**
     * <code>string thumbnail = 6;</code>
     * @return The bytes for thumbnail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThumbnailBytes() {
      return instance.getThumbnailBytes();
    }
    /**
     * <code>string thumbnail = 6;</code>
     * @param value The thumbnail to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnail(
        java.lang.String value) {
      copyOnWrite();
      instance.setThumbnail(value);
      return this;
    }
    /**
     * <code>string thumbnail = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbnail() {
      copyOnWrite();
      instance.clearThumbnail();
      return this;
    }
    /**
     * <code>string thumbnail = 6;</code>
     * @param value The bytes for thumbnail to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThumbnailBytes(value);
      return this;
    }

    /**
     * <code>string suggested_by = 7;</code>
     * @return The suggestedBy.
     */
    @java.lang.Override
    public java.lang.String getSuggestedBy() {
      return instance.getSuggestedBy();
    }
    /**
     * <code>string suggested_by = 7;</code>
     * @return The bytes for suggestedBy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSuggestedByBytes() {
      return instance.getSuggestedByBytes();
    }
    /**
     * <code>string suggested_by = 7;</code>
     * @param value The suggestedBy to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestedBy(
        java.lang.String value) {
      copyOnWrite();
      instance.setSuggestedBy(value);
      return this;
    }
    /**
     * <code>string suggested_by = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuggestedBy() {
      copyOnWrite();
      instance.clearSuggestedBy();
      return this;
    }
    /**
     * <code>string suggested_by = 7;</code>
     * @param value The bytes for suggestedBy to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestedByBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSuggestedByBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "title_",
            "artist_",
            "album_",
            "duration_",
            "thumbnail_",
            "suggestedBy_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0002\u0006\u0208\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo DEFAULT_INSTANCE;
  static {
    TrackInfo defaultInstance = new TrackInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TrackInfo.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TrackInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TrackInfo> PARSER;

  public static com.google.protobuf.Parser<TrackInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

