// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto
// Protobuf Java Version: 4.35.1

package com.mohsinraza.mohsinapexmusic.music.listentogether.proto;

/**
 * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload}
 */
@com.google.protobuf.Generated
public  final class TransferHostPayload extends
    com.google.protobuf.GeneratedMessageLite<
        TransferHostPayload, TransferHostPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload)
    TransferHostPayloadOrBuilder {
  private TransferHostPayload() {
    newHostId_ = "";
  }
  public static final int NEW_HOST_ID_FIELD_NUMBER = 1;
  private java.lang.String newHostId_;
  /**
   * <code>string new_host_id = 1;</code>
   * @return The newHostId.
   */
  @java.lang.Override
  public java.lang.String getNewHostId() {
    return newHostId_;
  }
  /**
   * <code>string new_host_id = 1;</code>
   * @return The bytes for newHostId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNewHostIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(newHostId_);
  }
  /**
   * <code>string new_host_id = 1;</code>
   * @param value The newHostId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setNewHostId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    newHostId_ = value;
  }
  /**
   * <code>string new_host_id = 1;</code>
   */
  private void clearNewHostId() {

    newHostId_ = getDefaultInstance().getNewHostId();
  }
  /**
   * <code>string new_host_id = 1;</code>
   * @param value The bytes for newHostId to set.
   */
  private void setNewHostIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    newHostId_ = value.toStringUtf8();

  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload)
      com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayloadOrBuilder {
    // Construct using com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string new_host_id = 1;</code>
     * @return The newHostId.
     */
    @java.lang.Override
    public java.lang.String getNewHostId() {
      return instance.getNewHostId();
    }
    /**
     * <code>string new_host_id = 1;</code>
     * @return The bytes for newHostId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNewHostIdBytes() {
      return instance.getNewHostIdBytes();
    }
    /**
     * <code>string new_host_id = 1;</code>
     * @param value The newHostId to set.
     * @return This builder for chaining.
     */
    public Builder setNewHostId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNewHostId(value);
      return this;
    }
    /**
     * <code>string new_host_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewHostId() {
      copyOnWrite();
      instance.clearNewHostId();
      return this;
    }
    /**
     * <code>string new_host_id = 1;</code>
     * @param value The bytes for newHostId to set.
     * @return This builder for chaining.
     */
    public Builder setNewHostIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNewHostIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "newHostId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload> parser = PARSER;
        if (parser == null) {
          synchronized (com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload)
  private static final com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload DEFAULT_INSTANCE;
  static {
    TransferHostPayload defaultInstance = new TransferHostPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TransferHostPayload.class, defaultInstance);
  }

  public static com.mohsinraza.mohsinapexmusic.music.listentogether.proto.TransferHostPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TransferHostPayload> PARSER;

  public static com.google.protobuf.Parser<TransferHostPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

